# 1. NUMPY BASICS

In [3]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

# Let's define a one-dimensional array 

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
# Let's create a numpy array from the list "my_list"
import numpy as np

In [6]:
my_list = list(range(1, 11))
my_list = list(map(lambda x: x**2, my_list))
my_list

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [7]:
x = np.array(my_list)
x

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
type(x)

numpy.ndarray

In [9]:
# Multi-dimensional (Matrix definition) 
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [10]:
y = np.array([[4,6,8,7], [20,5,6,9]])
y

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS 

In [11]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(10)
x

array([0.07353237, 0.7294323 , 0.99887826, 0.93654604, 0.13778196,
       0.74560866, 0.92618593, 0.08960887, 0.81357366, 0.69588253])

In [12]:
# you can create a matrix of random number as well
matrix = np.random.rand(5,5)
matrix

array([[0.91084315, 0.32322799, 0.77408103, 0.86227362, 0.08695231],
       [0.94405126, 0.71691425, 0.06247797, 0.14229334, 0.03357581],
       [0.77590797, 0.96932431, 0.19082567, 0.60604225, 0.53996447],
       [0.94635074, 0.40470439, 0.38932211, 0.88799493, 0.16583771],
       [0.91459514, 0.69870625, 0.58111253, 0.12961324, 0.71261868]])

In [13]:
# "randn()" normal distribution between 0 and 1
normal_distribution = np.random.randn(10)
normal_distribution

array([ 0.37433448,  0.36093721, -1.19895805, -0.95324527,  0.81952326,
       -0.87937068,  0.03469824,  1.27625333, -1.02899556,  0.95208755])

In [14]:
# "randint" is used to generate random integers between upper and lower bounds
random_integers = np.random.randint(1, 100, 10)
random_integers

array([59, 76, 82, 56, 40,  8, 12, 63, 41, 72])

In [15]:
# "randint" can be used to generate a certain number of random itegers as follows
random_integers = np.random.randint(1, 100, 10)
random_integers

array([52, 78, 21, 34, 67, 22, 81, 66,  3,  8])

In [16]:
# np.arange creates an evenly spaced values within a given interval
random_integers = np.arange(0, 10, 2)
random_integers

array([0, 2, 4, 6, 8])

In [17]:
# Create an evenly spaced values with a step of 5
array_by_5 = np.arange(0, 100, 5)
array_by_5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [18]:
# create a diagonal of ones and zeros everywhere else
diagonal = np.eye(5)
diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
# Array of ones
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [20]:
# Matrices of ones
matrix_of_ones = np.ones((5,5))
matrix_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# Array of zeros
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [22]:
x = int(input("Pls enter a positive integer: "))
x = np.random.randint(1, x, 20)
x

array([5, 1, 1, 7, 3, 9, 5, 4, 2, 1, 6, 5, 8, 9, 7, 4, 9, 1, 5, 6])

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [61]:
# Let's define a one-dimensional array 
my_list = [1, 2, 3, 4, 5,6]
my_list
x = np.array(my_list)
x

array([1, 2, 3, 4, 5, 6])

In [53]:
# Get Length of a numpy array
len(x)

5

In [54]:
# Get shape
x.shape

(5,)

In [55]:
# Obtain the datatype
x.dtype

dtype('int64')

In [63]:
# Reshape 1D array into a matrix
x.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
# Obtain the maximum element (value)
x.max()

6

In [65]:
# Obtain the minimum element (value)
x.min()

1

In [66]:
# Obtain the location of the max element
x.argmax()

5

In [67]:
# Obtain the location of the min element
x.argmin()

0

**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

In [74]:
my_list = np.arange(300, 500, 10)
my_list = my_list.reshape(4,5)
my_list

array([[300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490]])

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [76]:
my_second_list = np.random.randint(-1000, 1000, (20,20))
my_second_list.max()

995

# 4. MATHEMATICAL OPERATIONS

In [32]:
# np.arange() returns an evenly spaced values within a given interval


In [33]:
# Add 2 numpy arrays together


**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

# 5. SLICING AND INDEXING 

In [34]:
# Access specific index from the numpy array


In [35]:
# Starting from the first index 0 up until and NOT inlcluding the last element


In [36]:
# Broadcasting, altering several values in a numpy array at once


In [37]:
# Let's define a two dimensional numpy array


In [38]:
# Get a row from a mtrix


In [39]:
# Get one element


**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



# 6. ELEMENTS SELECTION (CONDITIONAL)

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [40]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

array([[[ 4,  6,  8,  7],
        [20,  5,  6,  9]]])

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [41]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

array([6, 3, 8, 4, 6, 4, 1, 9, 7, 6, 7, 3, 2, 7, 7, 7, 2, 3, 2, 1])

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [42]:
x = np.arange(300, 500, 10)
x.shape

(20,)

In [43]:
x = x.reshape(4, 5)
print(x)

[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [44]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

[[-290  411  507 -597  236 -561 -103 -998  442  -99 -184 -142  -24  159
   650 -976  356 -305  529  388]
 [ 336  237  799 -686  294  155  -89 -298 -931  214 -518 -573 -613 -774
  -265  435  648 -440  432 -434]
 [ 133 -148   82   98  164  365 -204 -441 -544 -173  181  880 -552  941
  -716  902 -898  344  422  542]
 [ 740  590  486 -198 -268  -49  174 -721  398 -468 -428  823  -10 -752
   -94 -141  -16 -580 -167  193]
 [ 711   14 -983 -767 -301 -621  671   96   59  147 -479  709   -5  593
  -678 -640   66  461   92  888]
 [-900  646 -239 -687 -945  551  766 -690  871  828 -483  614 -622  996
   568 -529 -955  430  772  214]
 [ 359  195 -851 -518  359  623   -6 -498 -803    1  100  565 -936  188
   797  238  293  170 -294  125]
 [-428 -948 -577 -162  785 -119  512 -808 -470  121 -776  289 -845 -237
   336 -618  704  508 -304  911]
 [-794  927 -152  606  205  295 -872 -344  443  855 -777 -101 -185  857
    -6  895  278 -459  438 -324]
 [ -97  770 -927  507 -545  -59 -159  339 -899 -324 -16

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [45]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

array([ 5.        , 20.88061302, 30.8058436 ])

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [46]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [47]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

In [48]:
X[:2, 3:]  = X[:2, 3:] * 2

In [49]:
X

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [50]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40, 25,  0],
       [25,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])