# 1. NUMPY BASICS

In [3]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

# Let's define a one-dimensional array 

In [4]:
pip install numpy

  Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Note: you may need to restart the kernel to use updated packages.


In [5]:
# Let's create a numpy array from the list "my_list"
import numpy as np

In [9]:
my_list = list(range(1, 11))
my_list = list(map(lambda x: x**2, my_list))
my_list

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [10]:
x = np.array(my_list)
x

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [11]:
type(x)

numpy.ndarray

In [13]:
# Multi-dimensional (Matrix definition) 
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [14]:
y = np.array([[4,6,8,7], [20,5,6,9]])
y

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS 

In [15]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(10)
x

array([0.92036176, 0.61584174, 0.79950003, 0.55802661, 0.43329351,
       0.45011004, 0.85957473, 0.91533683, 0.31474063, 0.77747411])

In [16]:
# you can create a matrix of random number as well
matrix = np.random.rand(5,5)
matrix

array([[0.16614999, 0.80002768, 0.88791657, 0.42192023, 0.55462026],
       [0.9347436 , 0.68492101, 0.19317321, 0.91577084, 0.29524179],
       [0.42549719, 0.75402085, 0.3557516 , 0.71086538, 0.87105287],
       [0.72431503, 0.05831082, 0.3118272 , 0.86926969, 0.25848615],
       [0.36984975, 0.66465032, 0.3402706 , 0.24101673, 0.04333277]])

In [17]:
# "randn()" normal distribution between 0 and 1
normal_distribution = np.random.randn(10)
normal_distribution

array([-0.62784636,  0.77233446,  1.60483344,  0.71161002, -0.63494509,
        0.71745027,  0.54909292, -2.66336478,  0.32441585, -0.35479486])

In [18]:
# "randint" is used to generate random integers between upper and lower bounds
random_integers = np.random.randint(1, 100, 10)
random_integers

array([80,  3, 25, 34, 14, 25, 46, 37, 82, 23])

In [19]:
# "randint" can be used to generate a certain number of random itegers as follows
random_integers = np.random.randint(1, 100, 10)
random_integers

array([ 8, 30, 68, 18, 40, 83,  9, 67, 62, 44])

In [21]:
# np.arange creates an evenly spaced values within a given interval
random_integers = np.arange(0, 10, 2)
random_integers

array([0, 2, 4, 6, 8])

In [22]:
# Create an evenly spaced values with a step of 5
array_by_5 = np.arange(0, 100, 5)
array_by_5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [24]:
# create a diagonal of ones and zeros everywhere else
diagonal = np.eye(5)
diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
# Array of ones
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [26]:
# Matrices of ones
matrix_of_ones = np.ones((5,5))
matrix_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# Array of zeros
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [30]:
x = int(input("Pls enter a positive integer: "))
x = np.random.randint(1, x, 20)
x

array([15, 25, 15, 13, 15,  9, 19, 10, 20,  1, 16, 21, 15, 23,  9,  4, 28,
       12, 15, 19])

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [ ]:
# Let's define a one-dimensional array 


In [ ]:
# Get Length of a numpy array


In [ ]:
# Get shape


In [ ]:
# Obtain the datatype


In [ ]:
# Reshape 1D array into a matrix


In [ ]:
# Obtain the maximum element (value)


In [ ]:
# Obtain the minimum element (value)


In [ ]:
# Obtain the location of the max element


In [ ]:
# Obtain the location of the min element


**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

# 4. MATHEMATICAL OPERATIONS

In [ ]:
# np.arange() returns an evenly spaced values within a given interval


In [ ]:
# Add 2 numpy arrays together


**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

# 5. SLICING AND INDEXING 

In [ ]:
# Access specific index from the numpy array


In [ ]:
# Starting from the first index 0 up until and NOT inlcluding the last element


In [ ]:
# Broadcasting, altering several values in a numpy array at once


In [ ]:
# Let's define a two dimensional numpy array


In [ ]:
# Get a row from a mtrix


In [ ]:
# Get one element


**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



# 6. ELEMENTS SELECTION (CONDITIONAL)

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [ ]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [ ]:
x = np.arange(300, 500, 10)
x.shape

In [ ]:
x = x.reshape(4, 5)
print(x)

**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [ ]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [ ]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

In [ ]:
X[:2, 3:]  = X[:2, 3:] * 2

In [ ]:
X

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X